### ISSUE TITLE
Build Issues (FATAL)

### ISSUE THREAD

**Issue by ghost** [tattn/SwiftExtensions#22]
<img width="273" alt="screen shot 2019-01-08 at 10 58 58 pm" src="https://user-images.githubusercontent.com/45888860/50876045-0f5a2200-1399-11e9-8e9b-b01ea79ccfc4.png">

I know how to fix the ones pertaining to `UIImage` and `UINib.OptionKey`

**Comment by tattn** [comment]
Sorry for late reply :bow:
Please try to build at master branch.

```bash
$ git stash # if you keep your changes
$ git checkout master
$ git pull origin master
```
