### ISSUE TITLE
Update for iOS 10+

### ISSUE THREAD

**Issue by SafelySwift** [tattn/SwiftExtensions#4]
In [UIImage extensions](https://github.com/tattn/SwiftExtensions/blob/master/Sources/UIImage%2B.swift), there is use of UIGraphics{Stuff}. In iOS 10 and later, there is a new type called UIGraphicsImageRenderer that optimized color space and leads to better performance.

**Comment by tattn** [comment]
Oh! I didn't know that at all!
`UIGraphicsImageRenderer` is a better way for iOS 10 :D

I will replace the old code with new code using `UIGraphicsImageRenderer` 😄

**Comment by SafelySwift** [comment]
Yeah - it optimized. For example if you only render alpha then in will use 1 byte and if you use srgb it will use 8. The other earlier way only used 4 bytes no matter what. 

Best,
Ethan

From, Ethan Uppal
Sent from my iPhone
Please excuse typos
